# fly.toml app configuration file generated for dilivery on 2025-06-21T03:49:32+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dilivery'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
