# fly.toml app configuration file generated for dilivery on 2025-06-21T03:49:32+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dilivery'
primary_region = 'fra'

[env]
PORT = "5000"

[build]

[[services]]
  internal_port = 5000
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[mounts]]
  source = "backups"
  destination = "/backups"

[[cron]]
  schedule = "0 2 * * *"
  command = "/backup.sh"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
